language: node_js
node_js:
  - 10.16.3
install: yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'gatsby-test-davincibot'
  skip_cleanup: true
  acl: public_read
  local_dir: public